---
- name: Converge
  hosts: all
  tasks:
    - name: Upgrade Powershell & Windows Management Framework to 5.1
      import_role:
        name: jpmat296.upgrade_powershell
    - name: Import tested role
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
