---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Execute Test-PendingReboot to assert no pending reboot
      win_shell: Test-PendingReboot -Detailed
      register: command
    - name: Assert no pending reboot
      assert:
        that:
         - "command.stdout is search(\"IsRebootPending\\s+: False\")"
